apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: network-loss-75-schedule
  namespace: chaos-mesh
spec:
  schedule: '@every 3s'
  historyLimit: 1
  concurrencyPolicy: 'Forbid'
  type: 'NetworkChaos'
  networkChaos:
    action: loss
    mode: 'fixed-percent'
    value: "75"
    selector:
      namespaces:
        - sock-shop
      expressionSelectors:
        - key: name
          operator: In
          values:
            - carts
            - catalogue
            - user
    loss:
      loss: "30"
      correlation: "0"
    duration: "1s"