apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: network-partition-75-schedule
  namespace: chaos-mesh
spec:
  schedule: '@every 3s'
  historyLimit: 1
  concurrencyPolicy: 'Forbid'
  type: NetworkChaos
  networkChaos:
    action: partition
    mode: 'fixed-percent'
    value: "75"
    selector:
      namespaces:
        - image-detection
    direction: both
    duration: "1s"
