apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: network-bandwidth-25-schedule
  namespace: chaos-mesh
spec:
  schedule: '@every 3s'
  historyLimit: 1
  concurrencyPolicy: 'Forbid'
  type: NetworkChaos
  networkChaos:
    action: bandwidth
    mode: 'fixed-percent'
    value: "25"
    selector:
      namespaces:
        - image-detection
    bandwidth:
      rate: "1Mbps"
      limit: 1000
      buffer: 1000
    duration: "1s"
