apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: network-partition-25-schedule
  namespace: chaos-mesh
spec:
  schedule: '@every 3s'
  historyLimit: 1
  concurrencyPolicy: 'Forbid'
  type: NetworkChaos
  networkChaos:
    action: partition
    mode: 'fixed-percent'
    value: "25"
    selector:
      namespaces:
        - sock-shop
      expressionSelectors:
        - key: name
          operator: In
          values:
            - carts
            - catalogue
            - user
    direction: both
    duration: "1s"
