apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: kill-75-containers-schedule
  namespace: chaos-mesh
spec:
  schedule: '@every 3s'
  historyLimit: 1
  concurrencyPolicy: 'Forbid'
  type: 'PodChaos'
  podChaos:
    action: 'container-kill'
    mode: 'fixed-percent'
    value: '75'
    selector:
      namespaces:
        - image-detection
      labelSelectors:
        app: 'cloud-detect' 
    containerNames:
      - cloud-detect-container
