apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: cpu-stress-25-pods-schedule
  namespace: chaos-mesh
spec:
  schedule: '@every 3s'
  historyLimit: 1
  concurrencyPolicy: 'Forbid'
  type: 'StressChaos'
  stressChaos:
    mode: 'fixed-percent'
    value: '25'
    selector:
      namespaces:
        - image-detection
      labelSelectors:
        app: 'cloud-detect'
    stressors:
      cpu:
        workers: 2
        load: 75
    duration: '1s'

# apiVersion: chaos-mesh.org/v1alpha1
# kind: Schedule
# metadata:
#   name: cpu-stress-25-pods-schedule
#   namespace: chaos-mesh
# spec:
#   schedule: '@every 3s'
#   historyLimit: 1
#   concurrencyPolicy: 'Forbid'
#   type: 'StressChaos'
#   stressChaos:
#     mode: 'fixed-percent'
#     value: '25'
#     selector:
#       namespaces:
#         - image-detection
#       labelSelectors:
#         app: 'cloud-detect'
#     stressors:
#       cpu:
#         workers: 2
#         load: 75
